server:
  port: 8081
spring:
  profiles:
    active: dev

person:
  name: zhangsan
  age: 12
  brith: 2018/04/22
  boss: false
  map: {k1: v1,k2: 12}
  list:
   - lisi
   - wangwu
  dog:
   name: uzi
   age: 5



---
server:
  port: 8083
spring:
  profiles: dev

---
server:
  port: 8084
spring:
  profiles: prod