server:
  port: 8088

spring:
  datasource:
    username: root
#    MySQL在高版本需要指明是否进行SSL连接
    url: jdbc:mysql://192.168.0.113:3306/mybatis?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

    # 数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

#  filters: stat,wall,log4j 中 log4j的存在报错
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#    spring boot 2.x 要运行sql文件，需要配置 initialization-mode: always
#    initialization-mode: always
#    schema:
#     - classpath:sql/department.sql
#     - classpath:sql/employee.sql
